### ISSUE TITLE
Finite difference Hessians?

### ISSUE THREAD

**Issue by chriselrod** [JuliaDiffEq/DiffEqDiffTools.jl#13]
My application needs Hessians, and I would rather not take Jacobians of gradients.
I could write up an implementation myself based on: http://www.sciencedirect.com/science/article/pii/S0377042707004086

**Comment by dextorious** [comment]
The reference looks good to me. If you want to write up an implementation, I'll be happy to review and pull it in. Otherwise, I can do it myself, but it will probably be a few days before I get to it.

**Comment by chriselrod** [comment]
I'll look at it more in a few hours. Diagonals are right, but I can't seem to get non-roughly zero off-diagonals with a simple test function (just a symmetric quadratic form, x' S x / 2).

**Comment by chriselrod** [comment]
The complex step methods seem to struggle when matrix or vector multiplication are involved:
```julia
julia> function x_plus_e_i!(y::Vector{S}, x::Vector{T}, i::Int, h::S = eps()*im) where S where T
           copy!(y, x)
           y[i] += h
           y
       end
x_plus_e_i! (generic function with 2 methods)

julia> S = randn(20,10) |> x -> x' * x; #positive definite matrix

julia> x = randn(10);

julia> f = x -> x' * S * x / 2 #Gradient = S * x; Hessian = S
(::#3) (generic function with 1 method)

julia> y = Vector{Complex{Float64}}(10);

julia> h = eps()
2.220446049250313e-16

julia> hi = h*im
0.0 + 2.220446049250313e-16im

julia> [imag(g(x_plus_e_i!(y, x, i, hi))) / h for i ∈ 1:10]'
1×10 RowVector{Float64,Array{Float64,1}}:
 0.726238  0.799128  0.71147  0.867147  0.758384  0.867052  -0.244029  0.150227  0.999054  0.477616

julia> cos.(x)'
1×10 RowVector{Float64,Array{Float64,1}}:
 0.726238  0.799128  0.71147  0.867147  0.758384  0.867052  -0.244029  0.150227  0.999054  0.477616

julia> [imag(f(x_plus_e_i!(y, x, i, hi))) / h for i ∈ 1:10]'
1×10 RowVector{Float64,Array{Float64,1}}:
 4.44089e-16  3.33067e-16  9.99201e-16  2.74086e-15  1.77636e-15  -5.55112e-16  7.77156e-16  2.22045e-15  5.55112e-17  8.88178e-16

julia> x' * S
1×10 RowVector{Float64,Array{Float64,1}}:
 -0.551427  1.58321  13.8398  16.0132  40.4378  -8.04598  -20.2981  -33.0481  -4.83252  37.1841

julia> g = x -> sum(sin, x)
(::#7) (generic function with 1 method)

julia> function floop(x::AbstractVector{T}, S::Matrix = S) where T
           out = zero(T)
           for i ∈ eachindex(x), j ∈ eachindex(x)
               out += x[i] * x[j] * S[j,i]
           end
           out / 2
       end
floop (generic function with 2 methods)

julia> [imag(floop(x_plus_e_i!(y, x, i, hi))) / h for i ∈ 1:10]'
1×10 RowVector{Float64,Array{Float64,1}}:
 -0.551427  1.58321  13.8398  16.0132  40.4378  -8.04598  -20.2981  -33.0481  -4.83252  37.1841
```

f was my test function while struggling to get the Hessian to provide anything other than zero for the off-diagonals.
Even the first derivatives fail on a simple quadratic form expressed as matrix multiplication.
But it works just fine if you turn the quadratic into a for loop -- but that is an awkward limitation to work around, and of course means one can't take advantage of BLAS.

**Comment by ChrisRackauckas** [comment]
Reference: https://v8doc.sas.com/sashtml/ormp/chap5/sect28.htm
And the complex form:
http://www.sciencedirect.com/science/article/pii/S0377042707004086

I'll implement these in the same manner that the Jacobians are now done. That shouldn't be so difficult.

**Comment by ChrisRackauckas** [comment]
Now that the others are in and the documentation is on the README, the general API of what the API should look like is pretty solidified. If you just follow how gradients and Jacobians look then it'll be great. So now someone just needs to tackle it!

**Comment by ChrisRackauckas** [comment]
I've ignored complex step for now since it seems to have issues, and AD is just better if you have that kind of control over f in this case.
