### ISSUE TITLE
Inplace functions for Jacobians

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDiffTools.jl#18]
Jacobians are on vector-valued functions, so it would make sense to allow `f(out,x)` instead of `out = f(x)`

**Comment by dextorious** [comment]
This will require another positional argument for something like `inplace_callable=Val{:false}`. Fast keyword arguments have rapidly become my number one language issue.

**Comment by ChrisRackauckas** [comment]
Yup it will. And I think it will be fine to handle it the diffeq way, where if the function is inplace then you treat it as though the `x` cannot do inplace operations. That way you have one path that's good for arrays, and the other is good for things like static arrays, and you can still go down the inplace path with anything else as well if you're silly.

>Fast keyword arguments have rapidly become my number one language issue.

Yup... I know about that feeling...
