### ISSUE TITLE
Cache type for Jacobians

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDiffTools.jl#20]
There should be a cache type for the Jacobians that generates the internal caches that are needed since different types of differentiation need different amounts of vectors. This is only needed for the inplace form since for out of place we can assume that allocating is trivial (static arrays).

**Comment by dextorious** [comment]
> This is only needed for the inplace form since for out of place we can assume that allocating is trivial (static arrays).

That's a fairly big assumption, IMO. I'm fine with it personally, but we might want to ask NLSolve / Optim people or any other potential users. Just a thought.

Apart from that, the general design question here is whether we unify everything in the cache type and expect the user to construct them (this cuts down on the positional arguments) or keep it merely for internal use.

**Comment by ChrisRackauckas** [comment]
I think like ForwardDiff we may just want to allow users to construct the cache type as an optimization. Then the dispatching can be done all on the cache type since that will know input and output types.

@pkofod ?

**Comment by pkofod** [comment]
^ agree

**Comment by ChrisRackauckas** [comment]
This is done. The Jacobian interface for mutable types is now pretty solid and allocation-free.
