### ISSUE TITLE
Sparsity support

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDiffTools.jl#29]
We can support sparsity in the in-place format (out of place doesn't really make sense anyways) by dispatching on the return type.

Currently there's no generic way to do this 

(https://github.com/JuliaLang/julia/issues/19372#issuecomment-360767745). 

That shows how sparse vectors can easily be handled.

But we can support sparse matrices like is shown there by simply looping over the non-zero elements like that. Our current kernels can be refactored to make use of stuff like:

https://pdfs.semanticscholar.org/ee06/57173bb0f0ed9571e205e970819346fb59de.pdf

for choosing the differencing and ordering. It might be nice to just handle the basic cases for that are easy to decouple, like tridiagonal and banded matrices, with a generic fallback that keeps output sparsity in tact without the computational advantage.

**Comment by ChrisRackauckas** [comment]
https://academic.oup.com/imamat/article/13/1/117/721987

**Comment by mauro3** [comment]
Yes, reviving this would be good.  Although, I don't have time and, as I'm not currently solving PDEs, neither urge.  Yes, transferring it to JuliaDiffEq would be good.  Also, maybe https://github.com/mbauman/RaggedArrays.jl would be a better dependence, but also stale.

**Comment by matthieugomez** [comment]
Support for BandedMatrix would be awesome, see https://github.com/JuliaMatrices/BandedMatrices.jl/issues/86

**Comment by ChrisRackauckas** [comment]
Indeed, that would be a nice one. In fact, that's probably the easiest coloring algorithm, right? There's no influence of the n+1th value on the 1st if there's a band size of n, so the seeding is just (1,0 (n times),1, 0 (n times), ...,0) then (0,1 (n times), 0, 1 (n times), .., 0 ). We plan on doing this for a GSoC, and this would be a good first step to get the interface together and set it up on the easy case of BandedMatrices.

**Comment by ChrisRackauckas** [comment]
Jacobians now allow for a color vector.
