### ISSUE TITLE
Size of Jacobian

### ISSUE THREAD

**Issue by hayatoikoma** [JuliaDiffEq/DiffEqDiffTools.jl#31]
In my understanding, the size of a Jacobian matrix is not necessarily square. As far as I read the code, there seems to be no way to specify the size of the output of ```f(x)``` . Is there any reason for it?(https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/src/jacobians.jl#L97)

**Comment by ChrisRackauckas** [comment]
That assumption only exists for the out-of-place form which is just a convenience function. If you supply a non-square Jacobian for the in-place form it should work.

**Comment by hayatoikoma** [comment]
I see. I didn't realize that I should have directly called ```finite_difference_jacobian!````.
Thank you for the explanation.
