### ISSUE TITLE
FInite diffrence Jacobian with Val{:complex} fails because `x` is not defined.

### ISSUE THREAD

**Issue by pkofod** [JuliaDiffEq/DiffEqDiffTools.jl#42]
See https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/2dc3c201ad0b1c568ce204f409ec2806000b32e4/src/jacobians.jl#L65 

The `Val{:complex}` branch looks up the type of a non-existent `x`.

**Comment by dextorious** [comment]
Should be fixed in #44, will close when merged.
