### ISSUE TITLE
Complex finite difference

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqDiffTools.jl#9]
It's an easy method where you take `epsilon = im` and take the imaginary of the result, and it's a poor man's autodiff that works very well. It would be a good option to have.

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.141.8002&rep=rep1&type=pdf

**Comment by dextorious** [comment]
Implemented in https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/commit/b76ba94580fd6d0bbba3ad981cf28342c900cd31
